- name: Put SELinux in permissive mode, logging actions that would be blocked.
  selinux:
    policy: targeted
    state: permissive
  tags:
    now    
- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled
  tags:
    now