# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "centos/7"
    config.vm.box_check_update = false
    config.vm.network "forwarded_port", id: "ssh", guest: 22, host: 2201
    config.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 512
      v.cpus = 1
    end
    config.vm.define "db1" do |db1|
      db1.vm.network "private_network", ip: "192.168.50.22"
      db1.vm.hostname = "db1"
    end
    config.vm.provision "shell",
      run: "always",
      inline: "ip route del default",
      inline: "ip route add default via 192.168.50.20"
  end
  


  #  config.vm.provision "ansible" do |ansible|
  #    ansible.verbose = "vvv"
  #    ansible.playbook = "playbook.yml"
  #    ansible.become = "true"
  #  end
  
  
    #config.vm.define "ansible" do |ansible|
    #  ansible.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "net1"
    #  ansible.vm.hostname = "ansible"
      #nfss.vm.provision "shell", path: "ansible_script.sh"
    #end
  
  
  
