---
- name: Install borgbackup
  yum:
    name: borgbackup
    state: present
  tags: borg

#- name: Download borg
#  ansible.builtin.get_url:
#    url: https://github.com/borgbackup/borg/releases/download/1.2.7/borg-linux64
#    dest: /usr/local/bin/borg
#    mode: '0755'
#  tags: borg

- name: Add the user 'borg' 
  ansible.builtin.user:
    name: borg
  tags: borg


- name: Create directory ~borg/.ssh
  ansible.builtin.file:
    path: ~borg/.ssh
    state: directory
    mode: '0700'
    owner: borg
    group: borg
  tags: borg

- name: make authorized_keys
  template:
    src: authorized_keys
    dest: ~borg/.ssh/authorized_keys
    mode: '0644'
    owner: borg
    group: borg
  tags: borg

...