---
#- name: Install epel
#  yum:
#    name: 
#      - epel-release
#    state: present

#- name: Install pip
#  yum:
#    name: 
#      - python-pip
#    state: present

 #здесь мы донастраиваем бд и юзера 
#- name: Make sure pymysql is present
#  become: true # needed if the other tasks are not played as root
#  pip:
#    name: pymysql
#    state: present

- name: Create a new database with name 'zabbix'
  community.mysql.mysql_db:
    name: zabbix
    state: present
    encoding:  utf8 
    collation: utf8_bin
#    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name:  set zabbix@localhost  and password
  mysql_user:
    name: zabbix
    password: "{{ mysql_system_password }}"
    host: localhost
    login_port: 3306
    priv: '*.*:ALL,GRANT'
    update_password: always
    state: present
#    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Set log_bin_trust_function_creators variable to 1 persistently
  community.mysql.mysql_variables:
    variable: log_bin_trust_function_creators
    value: 1
    mode: persist
#    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: root
    login_password: "{{ mysql_root_password }}"
  ignore_errors: True
  tags: now

- name: Allow zabbix connections
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 10051
    jump: ACCEPT
  tags: now


- name: installing zabbix repository.
  yum:
    name: https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
    state: present
    validate_certs: no
#  tags: now



- name: Install Zabbix server,  agent
  yum:
    name: 
      - zabbix-server-mysql 
      - zabbix-agent
      - centos-release-scl
    state: present
  #tags: now

- name: Install zabbix-web-mysql-scl , zabbix-nginx-conf-scl
  ansible.builtin.yum:
    name: 
    - zabbix-web-mysql-scl 
    - zabbix-nginx-conf-scl
    enablerepo: "zabbix-frontend"


- name: import initial schema and data. 
  shell: >-
    zcat /usr/share/doc/zabbix-server-mysql*/create.sql.gz | 
    mysql -u zabbix -p"{{ mysql_root_password }}" zabbix 
  ignore_errors: True


- name: disable log_bin_trust_function_creators 
  community.mysql.mysql_variables:
    variable: log_bin_trust_function_creators
    value: 0
    mode: persist
    login_user: root
    login_password: "{{ mysql_root_password }}"
  ignore_errors: True

- name:  change config  DBPassword  in /etc/zabbix/zabbix_server.conf
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_server.conf
    regexp: '^# DBPassword='
    line:  DBPassword={{ mysql_root_password }}
  tags: now


- name:   Configure NGINX for Zabbix frontend
  ansible.builtin.lineinfile:
    path: /etc/opt/rh/rh-nginx116/nginx/conf.d/zabbix.conf
    regexp: '^#        listen          80;'
    line:  '         listen          80;'

- name:   Configure NGINX for Zabbix frontend
  ansible.builtin.lineinfile:
    path: /etc/opt/rh/rh-nginx116/nginx/nginx.conf
    regexp: '        listen       80 default_server;'
    line:  '#         listen          80;'
  tags: now

#- name:   Configure PHP for Zabbix frontend
#  ansible.builtin.lineinfile:
#    path: /etc/opt/rh/rh-nginx116/nginx/conf.d/zabbix.conf
#    regexp: '^# server_name example.com;'
#    line:  server_name example.com;

- name:   Configure PHP for Zabbix frontend
  ansible.builtin.lineinfile:
    path: /etc/opt/rh/rh-php72/php-fpm.d/zabbix.conf
    regexp: '^listen.acl_users = apache'
    line:  listen.acl_users = apache,nginx

- name:   Configure PHP for Zabbix frontend
  ansible.builtin.lineinfile:
    path: /etc/opt/rh/rh-php72/php-fpm.d/zabbix.conf
    regexp: '^; php_value[date.timezone] = Europe/Riga'
    line: php_value[date.timezone] = Europe/Moscow

- name: Change conf zabbix.conf.php
  template:
    src: zabbix.conf.php
    dest: /etc/zabbix/web/zabbix.conf.php
    mode: '0644'

- name: Restart Services
  service:
    name: zabbix-server
    state: restarted
    enabled: yes
  tags: now

- name: Restart Services
  service:
    name: zabbix-agent
    state: restarted
    enabled: yes
  tags: now

- name: Restart Services
  service:
    name: rh-nginx116-nginx
    state: restarted
    enabled: yes
  tags: now

- name: Restart Services
  service:
    name: rh-php72-php-fpm
    state: restarted
    enabled: yes
  tags: now

#- name: root | place temporary cnf file
#  template:
#    src: temp_cnf.j2
#    dest: /etc/my.cnf
#    mode: '0644'

#- name: Start Mysql
#  service:
#    name: mysqld
#    state: started
#    enabled: yes

#- name: root | get temp root password
#  shell: >-
#    grep 'temporary password' /var/log/mysqld.log |
#    awk '{print $NF}' | tail -n 1
#  register: temp_root_pw
#  no_log: true
#  tags: now


#- name: root | set root password
#  shell: >-
#    mysqladmin -u root
#    --password="{{ temp_root_pw.stdout }}"
#    password "{{ mysql_root_password }}"
#  ignore_errors: True
  #no_log: true#
#  tags: now

#- name: Create a directory if it does not exist
#  ansible.builtin.file:
#    path: /etc/mysql/
#    state: directory
#    mode: '0755'

#- name: root | copy root.cnf
#  template:
#    src: root.cnf.j2
#    dest: /etc/mysql/root.cnf
#    mode: '0600'
#    owner: root
#    group: root

