---
- hosts: fw
  become:
    true
#  become_method:
#    su
#  become_user:
#    root
  remote_user:
    vagrant
  roles:
  - selinux
  - epel
  - nginx
  - php
  #- mysql
  - wordpress
  - zabbix-agent
  - rsyslog

...
   


  